// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: send_mail.proto

package com.rpc.mail;

public interface SendMailResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SendMailResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>optional string msg = 2;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>optional string msg = 2;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
