// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: send_mail.proto

package com.rpc.mail;

public final class SendMailServiceProto {
  private SendMailServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_SendMailRequest_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SendMailRequest_fieldAccessorTable;
  static com.google.protobuf.Descriptors.Descriptor
    internal_static_SendMailResponse_descriptor;
  static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SendMailResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017send_mail.proto\"D\n\017SendMailRequest\022\021\n\t" +
      "recipient\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\017\n\007conten" +
      "t\030\003 \001(\t\"-\n\020SendMailResponse\022\014\n\004code\030\001 \001(" +
      "\005\022\013\n\003msg\030\002 \001(\t2D\n\017SendMailService\0221\n\010sen" +
      "dMail\022\020.SendMailRequest\032\021.SendMailRespon" +
      "se\"\000B&\n\014com.rpc.mailB\024SendMailServicePro" +
      "toP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SendMailRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SendMailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SendMailRequest_descriptor,
        new java.lang.String[] { "Recipient", "Title", "Content", });
    internal_static_SendMailResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SendMailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SendMailResponse_descriptor,
        new java.lang.String[] { "Code", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
